(define-module (templates base)
  #:use-module (haunt html)
  #:use-module (haunt site)
  #:export (base-template))

(define (navigation)
  `(nav (@ (class "nav"))
        (div (@ (class "nav-brand"))
             (a (@ (href "/"))
                (span (@ (class "paren")) "(")
                "sexp-ed"
                (span (@ (class "paren")) ")")))
        (ul (@ (class "nav-links"))
            (li (a (@ (href "#intro")) "Intro"))
            (li (a (@ (href "#history")) "History"))
            (li (a (@ (href "#common-lisp")) "Common Lisp"))
            (li (a (@ (href "#scheme")) "Scheme"))
            (li (a (@ (href "#racket")) "Racket"))
            (li (a (@ (href "#clojure")) "Clojure"))
            (li (a (@ (href "#emacs-lisp")) "Emacs Lisp"))
            (li (a (@ (href "#janet")) "Janet"))
            (li (a (@ (href "#others")) "Others")))))

(define (footer)
  `(footer (@ (class "footer"))
           (div (@ (class "footer-content"))
                (p (@ (class "footer-parens"))
                   (span (@ (class "paren open")) "(")
                   "Made with "
                   (span (@ (class "heart")) "♥")
                   " and lots of parentheses"
                   (span (@ (class "paren close")) ")"))
                (p (@ (class "footer-links"))
                   "Contribute on "
                   (a (@ (href "https://github.com/ispringle/sexp-ed")
                         (target "_blank")
                         (rel "noopener noreferrer"))
                      "GitHub")))))

(define (base-template site content)
  `(html (@ (lang "en"))
         (head
          (meta (@ (charset "utf-8")))
          (meta (@ (name "viewport")
                   (content "width=device-width, initial-scale=1")))
          (title ,(site-title site) " - Learn Lisp")
          (meta (@ (name "description")
                   (content "A curated collection of resources to learn Lisp and its many dialects: Common Lisp, Scheme, Clojure, Racket, Emacs Lisp, Janet, and more.")))
          (link (@ (rel "preconnect")
                   (href "https://fonts.googleapis.com")))
          (link (@ (rel "preconnect")
                   (href "https://fonts.gstatic.com")
                   (crossorigin "")))
          (link (@ (rel "stylesheet")
                   (href "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700&family=Atkinson+Hyperlegible:wght@400;700&family=JetBrains+Mono:wght@400;500&display=swap")))
          (link (@ (rel "stylesheet")
                   (href "/assets/css/style.css"))))
         (body
          ,(navigation)
          (main (@ (class "main"))
                ,content)
          ,(footer))))
